SELECT A.CAR_ID, A.CAR_TYPE, ROUND(A.DAILY_FEE*30*(100-C.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON A.CAR_ID=B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
ON A.CAR_TYPE=C.CAR_TYPE
WHERE A.CAR_ID NOT IN
    (SELECT CAR_ID
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE>='2022-11-01' AND START_DATE<='2022-12-01')
AND C.DURATION_TYPE LIKE '30%'
GROUP BY CAR_ID
HAVING (FEE>=500000 AND FEE<2000000)
    AND A.CAR_TYPE IN ('세단','SUV')
ORDER BY FEE DESC, CAR_TYPE, A.CAR_ID DESC